const TEST_SERVER = 'TEST_SERVER'
const TEST_SERVER_SUCCESS = 'TEST_SERVER_SUCCESS'
const TEST_SERVER_FAILURE = 'TEST_SERVER_FAILURE'

export { TEST_SERVER, TEST_SERVER_SUCCESS, TEST_SERVER_FAILURE }
